import type { Subscription } from "@/types/subscription"

export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "1",
    name: "Netflix",
    billingInterval: "monthly",
    amountJpy: 790,
    standardAmountJpy: 1490,
    billingDayOfMonth: 5,
    billingMonth: 1,
    siteUrl: "https://www.netflix.com",
    status: "active",
  },
  {
    id: "2",
    name: "Spotify",
    billingInterval: "monthly",
    amountJpy: 480,
    standardAmountJpy: 980,
    billingDayOfMonth: 12,
    billingMonth: 1,
    siteUrl: "https://www.spotify.com",
    status: "active",
  },
  {
    id: "3",
    name: "GitHub",
    billingInterval: "monthly",
    amountJpy: 300,
    standardAmountJpy: 550,
    billingDayOfMonth: 28,
    billingMonth: 1,
    siteUrl: "https://github.com",
    status: "active",
  },
  {
    id: "6",
    name: "クラウドバックアップ（年契約）",
    billingInterval: "yearly",
    amountJpy: 9800,
    standardAmountJpy: 11800,
    billingDayOfMonth: 1,
    billingMonth: 4,
    siteUrl: "https://example.com",
    status: "active",
  },
  {
    id: "7",
    name: "開発ツール（四半期）",
    billingInterval: "quarterly",
    amountJpy: 4500,
    billingDayOfMonth: 15,
    billingMonth: 2,
    siteUrl: "https://example.com",
    status: "active",
  },
  {
    id: "4",
    name: "Adobe CC",
    billingInterval: "monthly",
    amountJpy: 6780,
    billingDayOfMonth: 15,
    billingMonth: 1,
    siteUrl: "https://www.adobe.com",
    status: "archived",
  },
  {
    id: "5",
    name: "Dropbox",
    billingInterval: "monthly",
    amountJpy: 1200,
    billingDayOfMonth: 1,
    billingMonth: 1,
    siteUrl: "https://www.dropbox.com",
    status: "archived",
  },
]
